################################################# Set theme  ##########################################

    
- id: '1627894507538'
  alias: set_theme
  trigger:
  - platform: state
    entity_id: input_select.themes
  - platform: homeassistant
    event: start
  action:
  - service: browser_mod.set_theme
    data_template:
      theme: '{{ states.input_select.themes.state }}'
  mode: single
################################################# Fibaro Check  ##########################################

- id: '1628506393892'
  alias: fibaro config problem
  description: ''
  trigger:
  - platform: state
    entity_id: sensor.hc_ground_temp
    to: 1True
  - platform: state
    entity_id: sensor.hc_basement_temp
    to: 1True
  - platform: state
    entity_id: sensor.hc_first_temp
    to: 1True
  - platform: state
    entity_id: sensor.hc_roof_temp
    to: 1True
  condition: []
  action:
  - data: {}
    service: homeassistant.restart
  mode: single
  
################################################# Restart HA  ##########################################
- id: '1628509048427'
  alias: Restart HA
  description: ''
  trigger:
  - platform: time
    at: 05:00:00
  condition: []
  action:
  - service: homeassistant.restart
  mode: single
################################################# Fibaro controller Check with sonoff ##########################################

- id: '1629642698213'
  alias: Basement controller checker
  description: ''
  trigger:
  - platform: template
    value_template: ''
    id: '{{states.sensor.hc_basement_temp.state  != "1True" }}'
  - platform: homeassistant
    event: start
  condition:
  - condition: template
    value_template: '{{states.sensor.hc_basement_temp.state  != "1True" }}'
  action:
  - service: switch.turn_off
    target:
      entity_id: switch.sonoff_basement
  - delay:
      hours: 0
      minutes: 1
      seconds: 0
      milliseconds: 0
  - service: switch.turn_on
    target:
      entity_id: switch.sonoff_basement
  mode: single
  
################################################# Notification to service mail  ##########################################  
  
- id: '1630243597324'
  alias: 'Service Notify Gmail '
  description: ''
  trigger:
  - platform: template
    value_template: '{{states.sensor.memory_use_percent.state |int >= 90 }}'
  - platform: template
    value_template: '{{states.sensor.processor_use_percent.state |int >= 90 }}'
  - platform: template
    value_template: '{{states.sensor.disk_use_percent_home.state |int >= 80 }}'
  - platform: template
    value_template: '{{states.sensor.processor_temperature.state |int >= 80 }}'
  - platform: template
    value_template: '{{states.sensor.hc_basement_temp.state  != "1True" }}'
  - platform: template
    value_template: '{{states.sensor.hc_first_temp.state  != "1True" }}'
  - platform: template
    value_template: '{{states.sensor.hc_ground_temp.state  != "1True" }}'
  - platform: template
    value_template: '{{states.sensor.hc_roof_temp.state  != "1True" }}'
  condition: []
  action:
  - choose:
    - conditions:
      - condition: template
        value_template: '{{states.sensor.memory_use_percent.state |int >= 90 }}'
      sequence:
      - service: notify.gmail
        data:
          message: RAM Up To 90%
          title: Attention!!
    - conditions:
      - condition: template
        value_template: '{{states.sensor.processor_use_percent.state |int >= 90 }}'
      sequence:
      - service: notify.gmail
        data:
          message: Processor Up To 90%
          title: Attention!!
    - conditions:
      - condition: template
        value_template: '{{states.sensor.disk_use_percent_home.state |int >= 80 }}'
      sequence:
      - service: notify.gmail
        data:
          message: Disk Up To 80% please Clear Dummy Data
          title: Attention!!
    - conditions:
      - condition: template
        value_template: '{{states.sensor.processor_temperature.state |int >= 80 }}'
      sequence:
      - service: notify.gmail
        data:
          message: Processor Temperature Up To 80 C the controller will be Fire
          title: Attention!!
    - conditions:
      - condition: template
        value_template: '{{states.sensor.hc_first_temp.state  != "1True" }}'
      sequence:
      - service: notify.gmail
        data:
          message: First Floor Fibaro Connection with HA might be issue, Please check
            it
          title: Attention!!
    - conditions:
      - condition: template
        value_template: '{{states.sensor.hc_ground_temp.state  != "1True" }}'
      sequence:
      - service: notify.gmail
        data:
          message: Ground Floor Fibaro Connection with HA might be issue, Please check
            it
          title: Attention!!
    - conditions:
      - condition: template
        value_template: '{{states.sensor.hc_basement_temp.state  != "1True" }}'
      sequence:
      - service: notify.gmail
        data:
          message: basement Floor Fibaro Connection with HA might be issue, Please
            check it
          title: Attention!!
    - conditions:
      - condition: template
        value_template: '{{states.sensor.hc_roof_temp.state  != "1True" }}'
      sequence:
      - service: notify.gmail
        data:
          message: Roof Floor Fibaro Connection with HA might be issue, Please check
            it
          title: Attention!!
    default: []
  mode: single
################################################# Stairs outo on   ##########################################
- id: '1622981987490'
  alias: Stairs lights on (manual)
  description: ''
  trigger:
  - entity_id: binary_sensor.living_room_roof_motion_sensor_78
    from: 'off'
    platform: state
    to: 'on'
  - entity_id: binary_sensor.corridor_first_stairs_m_s_60
    from: 'off'
    platform: state
    to: 'on'
  - entity_id: binary_sensor.unknown_ground_stairs_m_s_149
    from: 'off'
    platform: state
    to: 'on'
  condition:
  - after: input_datetime.stairs_time
    before: input_datetime.satirs_time_off
    condition: time
  action:
  - service: light.turn_on
    target:
      entity_id:
      - light.first_floor_stairs_ground_stairs_light_210
      - light.first_floor_stairs_first_stairs_light_211
  - delay:
      hours: 0
      minutes: 0
      seconds: 30
      milliseconds: 0
  - service: light.turn_off
    target:
      entity_id:
      - light.first_floor_stairs_ground_stairs_light_210
      - light.first_floor_stairs_first_stairs_light_211
  mode: single

################################################# Alarm Action  ##########################################

- id: '1594717388198'
  alias: Alarm action
  description: ''
  trigger:
  - entity_id: binary_sensor.entrance_entrance_m_s_143
    from: 'off'
    platform: state
    to: 'on'
  - entity_id: binary_sensor.corridor_first_stairs_m_s_60
    from: 'off'
    platform: state
    to: 'on'
  - entity_id: binary_sensor.dining_dining_shutter_m_s_137
    from: 'off'
    platform: state
    to: 'on'
  - entity_id: binary_sensor.dining_dining_window_m_s_131
    from: 'off'
    platform: state
    to: 'on'
  - entity_id: binary_sensor.entrance_villa_door_sensor_235
    from: 'off'
    platform: state
    to: 'on'
  - entity_id: binary_sensor.living_room_roof_motion_sensor_78
    from: 'off'
    platform: state
    to: 'on'
  - entity_id: binary_sensor.master_room_master_room_m_s_72
    from: 'off'
    platform: state
    to: 'on'
  - entity_id: binary_sensor.reception_reception_m_s_125
    from: 'off'
    platform: state
    to: 'on'
  - entity_id: binary_sensor.stairs_first_stairs_m_s_284
    from: 'off'
    platform: state
    to: 'on'
  condition:
  - condition: state
    entity_id: alarm_control_panel.home_alarm
    state: armed_home
  action:
  - data: {}
    entity_id: switch.unknown_siren_230
    service: switch.turn_on
  - data:
      message: Take Care !! someone in your Home 🚨🚨🚨
    service: notify.mobile_app_elatik_my_iphonex
    
################################################# Disarm Action  ##########################################  
- id: '1594717997024'
  alias: Disarm action
  description: ''
  trigger:
  - entity_id: alarm_control_panel.home_alarm
    from: armed_home
    platform: state
    to: disarmed
  condition: []
  action:
  - data: {}
    entity_id: switch.unknown_siren_230
    service: switch.turn_off
  - data:
      message: Your Home is Disarmed 🔓 🔓
    service: notify.mobile_app_elatik_my_iphonex
################################################# Arming Notification  ##########################################    
- id: '1595770887755'
  alias: Arming notification
  description: ''
  trigger:
  - entity_id: alarm_control_panel.home_alarm
    from: disarmed
    platform: state
    to: armed_home
  condition: []
  action:
  - data:
      message: Home is in Security Mode 🔒 🔒
    service: notify.mobile_app_elatik_my_iphonex
################################################# Gas Detection  ##########################################    
- id: '1594722773572'
  alias: Gas detection
  description: ''
  trigger:
  - entity_id: binary_sensor.kitchen_264_0_265
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - data: {}
    entity_id: switch.utilities_outdoor_gas_valve_219
    service: switch.turn_off
    
################################################# Landscape lights on  ##########################################    
- id: '1622375857858'
  alias: landscape lights1
  description: ''
  trigger:
  - platform: time
    at: input_datetime.landscape
  condition: []
  action:
  - service: light.turn_on
    data: {}
    target:
      entity_id:
      - light.unknown_258_2_263
      - light.unknown_258_1_262
      - light.outdoor_206_1_210
  - service: automation.turn_on
    target:
      entity_id: automation.landscape_off_time
  mode: single 
  
#################################################  Landscape lights off  ##########################################

- id: '1622387589369'
  alias: landscape off time
  description: ''
  trigger:
  - platform: time
    at: input_datetime.landscape_time_off
  condition: []
  action:
  - service: light.turn_off
    target:
      entity_id:
      - light.unknown_258_2_263
      - light.unknown_258_1_262
      - light.outdoor_206_1_210
  - service: automation.turn_off
    target:
      entity_id: automation.landscape_off_time
  mode: single


################################################# Intercom Notification  ##########################################
- id: '1623149662937'
  alias: notify intercom
  description: ''
  trigger:
  - platform: state
    entity_id: ' switch.unknown_325_1_329'
    to: 'on'
  condition: []
  action:
  - service: notify.mobile_app_a_iphone_12
    data:
      message: There is Someone Outside 🚪🔔
      data:
        url: /intercom-camera/camera
        entity_id: camera.fisheye
  mode: single
