
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

############ duckdns_portforward ############
 http:
  base_url: https://aswar21.duckdns.org
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem
################################################# Enable browser-mod ##########################################
browser_mod:
    prefix: 'browser_mod_'
    
stream:

weather:
# Text to speech
tts:
  - platform: google_translate
  

frontend:
        themes: !include_dir_merge_named themes
          
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

############Groups############
group: !include groups.yaml
cover: !include covers.yaml
light: !include lights.yaml

############ Restful API ############
rest_command: !include rest_command.yaml
############in climate group, you have to download climate_group from HACS integration
climate: 
  - platform: climate_group
    name: Villa AC
    entities:
        - climate.cinema_room_ac_1_degree_116
        - climate.gym_ac_2_degree_130
        - climate.family_room_ac_3_degree_149
        - climate.office_ac_1_degree_300
        - climate.dining_ac_2_degree_305
        - climate.reception_ac_3_degree_319
        - climate.kitchen_ac_4_degree_324
        - climate.living_room_ac_1_degree_94
        - climate.master_room_ac_2_degree_99
        - climate.room_1_ac_3_degree_104
        - climate.room_2_ac_4_degree_109
        

        
############Notification_config############        
notify:
  - name: "gmail"
    platform: smtp
    server: "smtp.gmail.com"
    port: 587
    timeout: 15
    sender: "acsacs429@gmail.com"

    username: "acsacs429@gmail.com"
    password: "Dcs5020-l"
    recipient:
      - "acsacs429@gmail.com"

    sender_name: "Aswar21_HomeAssistant"
################################################# Gateways ##########################################   
#in this section, select the desired gateway to configure
############ Fibaro ############    
fibaro:
  gateways: !include fibaro.yaml
            #   - url: http://192.168.1.32/api/   
            #     username: aswar21.fibaro@gmail.com
            #     password: Dcs502010-l 
            #   - url: http://192.168.1.33/api/  
            #     username: aswar21.fibaro@gmail.com
            #     password: Dcs502010-l 
            #   - url: http://192.168.1.31/api/  
            #     username: aswar21.fibaro@gmail.com
            #     password: Dcs502010-l 
            #   - url: http://192.168.1.30/api/  
            #     username: aswar21.fibaro@gmail.com
            #     password: Dcs502010-l 

############ Sonoff ############   
sonoff:
  username: aswar21.fibaro@gmail.com
  password: Dcs502010-l
  mode: local
  reload: always      
############ KNX ############ 

knx:

  cover: !include /config/KNX/knx_cover.yaml
  light: !include /config/KNX/knx_light.yaml
  binary_sensor: !include /config/KNX/knx_binary_sensor.yaml
  climate: !include /config/KNX/knx_climate.yaml
  sensor: !include /config/KNX/knx_sensor.yaml
  switch : !include /config/KNX/knx_switch.yaml
 
  tunneling:
    host: 192.168.1.138         #ip of knx gateway
    port: 3671
    local_ip: 192.168.1.180    #ip of HA
    
homekit:
- name: HASS Bridge 1
  port: 56332
  filter:
    include_domains:
      - climate
    include_entities: !include homekit_entities.yaml
   #- light.cinema_cinema_light_114
   #- light.cinema_front_left_spots_135
 
##################################################################################################
############Sensors############     
binary_sensor:
                          #check first floor controller connection to the network
  - platform: ping
    host: 192.168.1.32
    name: HC_first_ping
    count: 2
    scan_interval: 10
                              #check roof controller connection to the network
  - platform: ping
    host: 192.168.1.33
    name: HC_roof_ping
    count: 2
    scan_interval: 10


          #check ground controller connection to the network
  - platform: ping
    host: 192.168.1.31
    name: HC_ground_ping
    count: 2
    scan_interval: 10
    
                                #check basement controller connection to the network
  - platform: ping
    host: 192.168.1.30
    name: HC_basement_ping
    count: 2
    scan_interval: 10

    
   

sensor:
                          #HA system monitor sensors
  - platform: systemmonitor
    resources:
      - type: disk_use_percent
        arg: /home
      - type: memory_free
      - type: memory_use_percent
      - type: processor_use
      - type: last_boot
      - type: ipv4_address
        arg: eth0
      - type: network_in
        arg: eth0
      - type: packets_in
        arg: eth0
      - type: packets_out
        arg: eth0
      - type: processor_temperature
      - type: last_boot
      
  - platform: rest
    resource: http://192.168.1.32/api/loginStatus
    name: HC_first_api_check
    value_template: '{{ value_json.status }}'
    username: aswar21.fibaro@gmail.com
    password: Dcs502010-l
  - platform: template
    sensors:
      hc_first_temp:
        friendly_name: "HC first temp"
        unit_of_measurement: "째"
        value_template: "1{{ states.sensor.hc_first_api_check.state }}"   
        
  - platform: rest
    resource: http://192.168.1.33/api/loginStatus
    name: HC_roof_api_check
    value_template: '{{ value_json.status }}'
    username: aswar21.fibaro@gmail.com
    password: Dcs502010-l
  - platform: template
    sensors:
      hc_roof_temp:
        friendly_name: "HC roof temp"
        unit_of_measurement: "째"
        value_template: "1{{ states.sensor.hc_roof_api_check.state }}"   
        
  - platform: rest
    resource: http://192.168.1.31/api/loginStatus
    name: hc_ground_api_check
    value_template: '{{ value_json.status }}'
    username: aswar21.fibaro@gmail.com
    password: Dcs502010-l
  - platform: template
    sensors:
      hc_ground_temp:
        friendly_name: "HC ground temp"
        unit_of_measurement: "째"
        value_template: "1{{ states.sensor.hc_ground_api_check.state }}"   
        
        
  - platform: rest
    resource: http://192.168.1.30/api/loginStatus
    name: hc_basement_api_check
    value_template: '{{ value_json.status }}'
    username: aswar21.fibaro@gmail.com
    password: Dcs502010-l
  - platform: template
    sensors:
      hc_basement_temp:
        friendly_name: "HC basement temp"
        unit_of_measurement: "째"
        value_template: "1{{ states.sensor.hc_basement_api_check.state }}"   
        

    
################################################## Alarm Panel ##################################################################
alarm_control_panel:
  - platform: manual
    name: Home Alarm
    code: '1234'
    arming_time: 10
    delay_time: 5
    trigger_time: 4
    disarmed:
      trigger_time: 0
    armed_home:
      arming_time: 0
      delay_time: 0

################################################# Cameras  ##########################################    

camera:
  - platform: ffmpeg
    name: Default Camera 
    input: rtsp://admin:Dcs502010-l@192.168.1.21:554
  - platform: ffmpeg
    name: Hikvision Camera
    input: rtsp://admin:Dcs502010-l@192.168.1.22:554/Streaming/Channels/101
  - platform: ffmpeg
    name: Samsung Camera
    input: rtsp://admin:Dcs502010-l@192.168.1.21:554/profile4/media.smp
  - platform: mjpeg
    name: Panasonic Camera
    still_image_url: http://192.168.100.241/image.jpg
    mjpeg_url: http://admin:Ayman%40123@192.168.100.241/axis-cgi/mjpg/video.cgi?date=1&clock=1&camera=0&resolution=220x140
    
  - platform: ffmpeg
    name: Ezviz Camera
    input: rtsp://admin:GXEAHM@192.168.86.112:554/H.264
    
  - platform: generic
    name: EZ-IP Camera
    still_image_url: http://192.168.1.206/jpg/image.jpg
    stream_source: rtsp://admin:admin123@192.168.1.206/cam/realmonitor?channel=1&subtype=00&authbasic=YWRtaW46YWRtaW4xMjM=
  - platform: mjpeg
    name: Dlink Camera 1
    still_image_url: http://192.168.1.65/image.jpg
    mjpeg_url:  http://admin:dcs5020l@192.168.1.65/mjpeg.cgi?user=admin&password=dcs5020l&channel=6
  - platform: ffmpeg
    name: Dlink Camera 2
    input: rtsp://admin:dcs5020l@192.168.1.44/live3.sdp
 


################################################# Cameras proxy   ##########################################     
  - platform: proxy
    entity_id: camera.camera_1
    name: camera1 stream
 
    max_image_width: 480
    max_image_height: 320
    max_stream_width: 480
    max_stream_height: 320
    image_left: 100
    image_refresh_rate: 2.0   

    
################################################## Human detection  ##################################################################           
    
image_processing:
  - platform: doods
    url: "http://192.168.1.245:8080"
    scan_interval: 0.5
    detector: tensorflow         #-----------------------------------you can change this to (defualt)
    source:
      - entity_id: camera.camera1
    file_out: /config/www/camera1.jpg
    confidence: 80

################################################# Media  ##########################################     
    
webostv:
  - host: 192.168.1.50
    name: Family Room TV
  - host: 192.168.1.51
    name: Gym TV
  - host: 192.168.1.54
    name: Kitchen TV

media_player:

  - platform: onkyo
    host: 192.168.1.53
    name: Cinema onkyo
 #   max_volume : 200
    sources:
       pc: "HTPC"
       dvd: "DVD"
       cd: "CD"
       tv-tape: "TV-Tape"
       tv-cd: "TV-CD"
       bd-dvd: "BD-DVD"
       usb: "USB"
       multi-ch: "Multi-CH"
       universal-port: "UNIVERSAL-PORT"
       video1: "VIDEO1"
       video2: "VIDEO2"
################################## Samsung tizen Old version #####################

  - platform: samsungtv_tizen   #Family TV
    name: Family TV
    host: 192.168.1.4

    mac: F4:FE:FB:36:87:48
    api_key: 823f9b68-e2bb-43dc-8a3e-bac0a10f42bd   ########## token
    device_id: 36ce419d-99af-2480-61da-40132cdb9e75 ####### from smartthings URL
    scan_app_http: false
    show_channel_number: true
    update_method: "smartthings"
    source_list: '{ "Source": "KEY_SOURCE",
        "TV": "KEY_TV" ,
        "HDMI": "KEY_HDMI" ,
        "netflix": "KEY_SOURCE+KEY_RIGHT+KEY_RIGHT+KEY_ENTER" ,
        "youtube": "KEY_SOURCE+KEY_RIGHT+KEY_RIGHT+KEY_RIGHT+KEY_ENTER" ,   
        "soptify": "KEY_SOURCE+KEY_RIGHT+KEY_RIGHT+KEY_RIGHT+KEY_RIGHT+KEY_ENTER" ,  
        "prime": "KEY_SOURCE+KEY_RIGHT+KEY_RIGHT+KEY_RIGHT+KEY_RIGHT+KEY_RIGHT+KEY_ENTER" ,  
         "ONKYO": "ST_HDMI2" ,
        "AmbientMode": "KEY_AMBIENT" 
                 }'
    app_list: '{
        "YouTube": "111299001912/9Ur5IzDKqV.TizenYouTube",
        "Spotify": "3201606009684" ,
        "Netflix": "RN1MCdNq8t.Netflix/11101200001/org.tizen.netflix-app",
        "Movies & TV Google Play": "3201601007250" ,
        "Prime Video": "3201512006785/org.tizen.ignition" ,
        "Deezer": "cexr1qp97S.Deezer" 
    
                 }'
 
  

############ Samsung Tizen TV ############
samsungtv_smart:
# Family TV
  - host: 192.168.100.4
    source_list: '{"TV": "ST_TV", "HDMI1": "ST_HDMI1", "HDMI2": "ST_HDMI2", "HDMI3": "ST_HDMI3"}'
    app_list: '{"Netflix": "3201907018807/org.tizen.netflix-app", "YouTube": "111299001912/9Ur5IzDKqV.TizenYouTube", "Spotify": "rJeHak5zRg.Spotify" ,"Prime Video": "3201910019365/org.tizen.primevideo"}'



############ Logger for any integration ############
logger:
  default: info
  logs:
    homeassistant.components.smartthings: debug       
