type: vertical-stack
width: 90%
cards:
  - type: custom:mod-card
    style: |
      ha-card {
        # padding: 10px;
        border-radius: 30px 30px 0px 0px;
        backdrop-filter: blur(15px);
        -webkit-backdrop-filter: blur(30px);
        background: rgba(0,0,0,0);
      }
    card:
      type: custom:layout-card
      layout_type: grid
      cards:
        - type: custom:button-card
          entity: input_select.devices_landscape
          view_layout:
            grid-area: lights
          template: select_lights
          icon: ios:lightbulb

        - type: custom:button-card
          entity: input_select.devices_landscape
          view_layout:
            grid-area: shutter
          icon: mdi:blinds
          template: select_shutters

        # - type: custom:button-card
        #   entity: input_select.devices_landscape
        #   view_layout:
        #     grid-area: ac
        #   icon: mdi:air-conditioner
        #   template: select_ac

        - type: custom:button-card
          entity: input_select.devices_landscape
          view_layout:
            grid-area: more
          icon: mdi:chevron-double-down
          template: select_more_scene

      layout:
        grid-auto-columns: minmax(1fr,auto)
        grid-coulmn-gap: 0px
        grid-template-areas: |
          "lights shutter  more"
        place-items: center
        mediaquery:
          "(max-width: 800px)":
            .: |
              ha-card {
                 background-color: 'linear-gradient(to bottom, #c32650, #f15a29)';
                          }
            grid-auto-columns: minmax(1fr,auto)
            grid-coulmn-gap: 0px
            grid-auto-rows: minmax(1fr,auto)
            grid-template-areas: |
              "lights shutter   more"
          "(max-width: 1200px)":
            grid-gap: var(--custom-layout-card-padding)
            grid-auto-columns: 1fr 1fr 1fr
            grid-auto-rows: minmax(1fr,auto)
            grid-template-areas: |
              "lights shutter  more"
